apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: allow-priv-esca
  name: allow-priv-esca
spec:
  containers:
  - image: nginx
    name: allow-priv-esca
    securityContext:
      allowPrivilegeEscalation: false
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
